### ISSUE TITLE
Best practice for logging 100k messages in one go

### ISSUE THREAD

**Issue by suryatech** [phuesler/ain#36]
Really appreciate your efforts towards this.

I was wondering how you'd send 100k messages to syslog at once. I tried invoking the Syslog.send function in a loop and that doesn't seem to work at this scale.

Thoughts?

**Comment by phuesler** [comment]
Let me start by saying that Ain is not designed to handle this use case and probably never will. The last test that I did topped out at around 1800 messages per second on a MacBook Air.

Anyway, I'll write down a few ideas and considerations that come to mind:

* Is is as much about ain sending the messages at it is about syslog processing the messages at that rate. Let's assume that the receiver off the messages is able to handle the load
* Ain is mostly I/O bound except the little computations it needs to compose the messages
* Node runs on 1 core only. You could try to run several node processes. However I'm not sure this will help, because it is mostly I/O that we are doing.
* Increase the number of sockets that ain uses
* Run serveral instances of ain in the same node process (similar to above)
* The heavy lifting is done by the kernel (unix socket, udp socket). sysctl kernel tweaking might help
* UDP is unreliable (by design). Being able to pump out 100k messages per second doesn't mean they will also arrive

**Comment by suryatech** [comment]
Completely agree with the fact that Ain is not intended to perform this.

We ended up forking a child process that would use the ```logger``` cli utility along with some native node.js streams magic to log information to syslog.

Thanks for your perspective though. :)

**Comment by phuesler** [comment]
I thought you might be interested in this article https://blog.cloudflare.com/how-to-receive-a-million-packets/

**Comment by suryatech** [comment]
@phuesler Very insightful. Thanks for sharing!
